# Generated by Django 4.1.1 on 2022-09-23 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atividade',
            new_name='Robos',
        ),
    ]
